apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: test
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP