apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: test
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: fratris/sushi-frontend:test-release
        ports:
        - containerPort: 80


apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: test
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30301
