apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: test
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: fratris/sushi-frontend:test-release
        ports:
        - containerPort: 80


apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: test
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
