apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: test
spec:
  type: LoadBalancer
  selector:
    name: frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP