apiVersion: apps/v1
kind: Deployment
metadata:
  name: parser-deployment
  namespace: test
  labels:
    app: parser
    env: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: parser
  template:
    metadata:
      labels:
        app: parser
    spec:
      containers:
      - name: parser
        image: fratris/sushi-parser:test-release
        ports:
        - containerPort: 8000


apiVersion: v1
kind: Service
metadata:
  name: parser-service
  namespace: test
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: parser
  ports:
    - port: 8000
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 8000
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30302
