apiVersion: v1
kind: Service
metadata:
  name: parser-service
  namespace: test
spec:
  type: LoadBalancer
  selector:
    app: parser
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
