apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  namespace: test
spec:
  type: LoadBalancer
  selector:
    name: webserver
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP