apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
  namespace: test
  labels:
    app: webserver
    env: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: fratris/sushi-parser:test-release
        ports:
        - containerPort: 8081


apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: test
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - port: 8081
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 8081
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30303
